### ISSUE TITLE
编译出来的固件自带NAT66

### ISSUE THREAD

**Issue by missing233** [chenmozhijin/OpenWrt-K#39]
具体表现为LAN侧设备虽然能分配到公网IPv6，但是测试IP地址时显示的IPv6地址是路由器bridge的IP或者WAN6的IP
不了解这个功能的开关在哪里，似乎官方firmware selector里的固件没有这个问题。

**Comment by chenmozhijin** [comment]
试一下把网络 -- 接口 -- 全局网络选项 中的"IPv6 ULA 前缀"留空

**Comment by chenmozhijin** [comment]
我不是很明白你的意思，你说的“bridge IP或者WAN6的IP”指的是什么。

不过你可以试试下列设置项有没有你想要的。

网络 -- 接口 » 每个接口中的高级设置 -- 委托 IPv6 前缀


网络 -- 接口 » lan -- DHCP 服务器 -- IPv6 设置

我目前的网络状况：
<img width="326" alt="09-15 015437" src="https://github.com/chenmozhijin/OpenWrt-K/assets/110812055/6e1f673f-a807-4338-8e41-fee216d5d473">
![image](https://github.com/chenmozhijin/OpenWrt-K/assets/110812055/466a7d98-a3bf-4618-9497-9fcc3ef63a0a)

我目前的配置：
<img width="1529" alt="2023-09-15 015841" src="https://github.com/chenmozhijin/OpenWrt-K/assets/110812055/f4ee960a-0ff6-41d4-bcf3-b35a76fa9aa5">
<img width="1710" alt="2023-09-15 020047" src="https://github.com/chenmozhijin/OpenWrt-K/assets/110812055/6f65543f-a817-4aeb-b6b2-7710b9a0085d">
<img width="1673" alt="2023-09-15 020153" src="https://github.com/chenmozhijin/OpenWrt-K/assets/110812055/a91d7aac-8825-4434-89be-09e652f32e90">
<img width="1704" alt="2023-09-15 020137" src="https://github.com/chenmozhijin/OpenWrt-K/assets/110812055/db5afc7f-ba60-4dd9-aba9-295864b9c0c4">
<img width="1232" alt="2023-09-15 020107" src="https://github.com/chenmozhijin/OpenWrt-K/assets/110812055/28003c85-c8dc-45f0-830d-ecb784d4baff">

**Comment by chenmozhijin** [comment]
好像确实是这样，但是我试了一下，关闭openwrt的防火墙，手机用流量确实也能访问我PC获取的IPv6地址。
这很奇怪但好像并没有什么影响。

我的首次启动时运行脚本（uci-defaults）并没有修改网络相关的配置,如果[官方firmware selector里的固件](https://firmware-selector.openwrt.org/?version=23.05.0-rc3&target=x86%2F64&id=generic)没有这个问题则可能是其他插件或openwrt的版本不同导致的。

**Comment by chenmozhijin** [comment]
感谢反馈。
我已在Turbo ACC 网络加速设置中添加默认关闭的“IPv6 全锥形 NAT”开关（见 
 https://github.com/chenmozhijin/turboacc/commit/3b630084c97aa040bed5341eb80bca1be8092ecb ）。
<img width="1717" alt="image" src="https://github.com/chenmozhijin/OpenWrt-K/assets/110812055/59eeec2c-1ba6-467a-8e93-53d060479efa">
