### ISSUE TITLE
怎么修改主机名称

### ISSUE THREAD

**Issue by yndzm** [chenmozhijin/OpenWrt-K#50]
在openwrtext.config添加hostname=OpenWrt后不起作用，还是OpenWrt-K

**Comment by chenmozhijin** [comment]
替换下面的OpenWrt-k
https://github.com/chenmozhijin/OpenWrt-K/blob/d865af0460f591315d5bce05d2b26e01e2eb86cc/.github/workflows/build-openwrt.yml#L714

**Comment by yndzm** [comment]
谢谢
