### ISSUE TITLE
大佬考虑采用这个PR来加速编译速度吗？

### ISSUE THREAD

**Issue by wanmyj** [chenmozhijin/OpenWrt-K#52]
### Discussed in https://github.com/chenmozhijin/OpenWrt-K/discussions/51

<div type='discussions-op-text'>

<sup>Originally posted by **wanmyj** October 31, 2023</sup>
https://github.com/coolsnowwolf/lede/pull/7796
偶然发现lede的repo里有这个open的PR，好像采用了cache缓存工具链，我对action也不是很懂，不知道能不能应用到大佬的仓库里。

我看大家的action都是5hour左右，如果能降到一小时以内，会方便很多</div>

**Comment by chenmozhijin** [comment]
我以前也看到过这个PR，不过它是两年前的到现在还没有合并，根据下面的评论来看问题也不少。

这个方法节省的是编译工具与编译工具链的时间，一般加起来不到一个小时。
想要5小时左右降到一小时以内这个方法是行不通的。

不过很多时候重复编译的时后都只更新了一两个包，只要内核与内核模块不更新就可以使用上一次的未更新的包加上使用sdk重新编译的更新了的包，直接送到build-Image job中构建镜像，这样倒有可能降到一小时以内，不过可能会出现兼容性问题。

虽然想法还行不过最近我都没有什么时间，等有空了可以试试。
