### ISSUE TITLE
请教：如何修改可以编译通过https://github.com/asvow/luci-app-tailscale呢？

### ISSUE THREAD

**Issue by hexsen929** [chenmozhijin/OpenWrt-K#63]
沉默大佬你好，我这两天在折腾 https://github.com/asvow/luci-app-tailscale，作者的编译需要先执行
`sed -i '/\/etc\/init\.d\/tailscale/d;/\/etc\/config\/tailscale/d;' feeds/packages/net/tailscale/Makefile`

请问可以将这段代码加到哪个位置呢，我现在加到fix_problem.sh的最后一行，不知道有效吗，还在编译中，要两个多小时，先跑来问问，对这个一窍不通

**Comment by chenmozhijin** [comment]
加到fix_problem.sh中应该是有效的
不过https://github.com/hexsen929/OpenWrt-K/commit/4e9cacc0f0bc7227876f43d135e4284436f6a1b9应该就没有什么用了

**Comment by hexsen929** [comment]
感谢，不过编译失败了，可能是他源码哪里不兼容。
