### ISSUE TITLE
使用配置文件构建配置时，有乱码

### ISSUE THREAD

**Issue by rheatin** [chenmozhijin/OpenWrt-K#70]
<img width="724" alt="image" src="https://github.com/user-attachments/assets/edc597f5-9794-4aa0-ae26-6c1d4f108f63">

**Comment by chenmozhijin** [comment]
这应该是你系统的问题

脚本是UTF-8 编码的你需要保证你终端的编码是UTF-8

试试运行脚本前执行以下命令
```sh
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```
这可能可以解决你的问题

**Comment by rheatin** [comment]
谢谢，解决啦，当时是还以为没有安装中文呢= =
