### ISSUE TITLE
lucky是不是不兼容，编译不上

### ISSUE THREAD

**Issue by yndzm** [chenmozhijin/OpenWrt-K#78]
我手动安装ipk也报错，但是可以显示，web服务无法使用，好像是防火墙不兼容，还有我编译出来的固件跟北京时间相差8小时

**Comment by chenmozhijin** [comment]
时区问题应该已经修复 2bc0890c4e5048c3ef79e174db5cea7f20bc788e 
lucky还有问题吗？
